clients/urls.py
from django.urls import path
from clients import views

app_name = "clients"

urlpatterns = [
    path('list/', views.ListClients.as_view(), name="cl_list"),
    path('add/', views.AddClient.as_view(), name="cl_add"),
    path('detail/<int:pk>/', views.DetailClient.as_view(), name="cl_detail"),
    path('update/<int:pk>/', views.UpdateClient.as_view(), name="cl_update"),
    path('delete/<int:pk>/', views.DeleteClient.as_view(), name="cl_delete"),

]

employees/urls.py
from django.urls import path
from employees import views

app_name = "employees"

urlpatterns = [
    path('list/', views.ListEmployees.as_view(), name="em_list"),
    path('add/', views.AddEmployee.as_view(), name="em_add"),
    path('detail/<int:pk>/', views.DetailEmployee.as_view(), name="em_detail"),
    path('update/<int:pk>/', views.UpdateEmployee.as_view(), name="em_update"),
    path('delete/<int:pk>/', views.DeleteEmployee.as_view(), name="em_delete"),
    path('position/list/', views.ListPositions.as_view(), name="pos_list"),
    path('position/add/', views.AddPosition.as_view(), name="pos_add"),
    path('position/detail/<int:pk>/', views.DetailPositions.as_view(), name="pos_detail"),
    path('position/update/<int:pk>/', views.UpdatePositions.as_view(), name="pos_update"),
    path('position/delete/<int:pk>/', views.DeletePositions.as_view(), name="pos_delete"),
]

home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
]

provider/urls.py
from django.urls import path
from provider import views

app_name = "provider"

urlpatterns = [
    path('list/', views.ListProvider.as_view(), name="pr_list"),
    path('add/', views.AddProvider.as_view(), name="pr_add"),
    path('detail/<int:pk>/', views.DetailProvider.as_view(), name="pr_detail"),
    path('update/<int:pk>/', views.UpdateProvider.as_view(), name="pr_update"),
    path('delete/<int:pk>/', views.DeleteProvider.as_view(), name="pr_delete"),
]

sgip/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('clients/', include('clients.urls')),
    path('employees/', include('employees.urls')),
    path('providers/', include('provider.urls')),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.
class Index(generic.View):
    template_name = "home/index.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Abraham Matehuala Valenzuela"
        }
        
        return render(request, self.template_name, self.context)

templates/home/index.html
{% extends "base/base.html" %}

{% block title %}
Home
{% endblock title %}

{% block content %}
<br>
<div class="row">
    <div class="col-sm-4 d-grid gap-2">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Clients</h5>
          <p class="card-text">See the CRUD for the clients in SGIP</p>
          <a href="{% url 'clients:cl_list' %}" class="btn btn-primary d-grid">Go to Clients</a>
        </div>
      </div>
    </div>
    <div class="col-sm-4 d-grid gap-2">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Employees</h5>
          <p class="card-text">See the CRUD for the employees in SGIP</p>
          <a href="{% url 'employees:em_list' %}" class="btn btn-primary d-grid">Go to Employees</a>
        </div>
      </div>
    </div>
    <div class="col-sm-4 d-grid gap-2">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Providers</h5>
            <p class="card-text">See the CRUD for the providers in SGIP</p>
            <a href="{% url 'provider:pr_list' %}" class="btn btn-primary d-grid">Go to Providers</a>
          </div>
        </div>
      </div>
</div>
<br>
{% endblock content %}