clients/urls.py
from django.urls import path
from clients import views

app_name = "clients"

urlpatterns = [
    path('list/', views.ListClients.as_view(), name="cl_list"),
    path('add/', views.AddClient.as_view(), name="cl_add"),
    path('detail/<int:pk>/', views.DetailClient.as_view(), name="cl_detail"),
    path('update/<int:pk>/', views.UpdateClient.as_view(), name="cl_update"),
    path('delete/<int:pk>/', views.DeleteClient.as_view(), name="cl_delete"),

]

employees/urls.py
from django.urls import path
from employees import views

app_name = "employees"

urlpatterns = [
    path('list/', views.ListEmployees.as_view(), name="em_list"),
    path('add/', views.AddEmployee.as_view(), name="em_add"),
    path('detail/<int:pk>/', views.DetailEmployee.as_view(), name="em_detail"),
    path('update/<int:pk>/', views.UpdateEmployee.as_view(), name="em_update"),
    path('delete/<int:pk>/', views.DeleteEmployee.as_view(), name="em_delete"),
    path('position/list/', views.ListPositions.as_view(), name="pos_list"),
    path('position/add/', views.AddPosition.as_view(), name="pos_add"),
    path('position/detail/<int:pk>/', views.DetailPositions.as_view(), name="pos_detail"),
    path('position/update/<int:pk>/', views.UpdatePositions.as_view(), name="pos_update"),
    path('position/delete/<int:pk>/', views.DeletePositions.as_view(), name="pos_delete"),
]

home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
]

sgip/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('clients/', include('clients.urls')),
    path('employees/', include('employees.urls')),
    path('providers/', include('provider.urls')),
]

employees/models.py
from django.db import models

# Create your models here.
class Positions(models.Model):
    pos_name = models.CharField(max_length=255)

    def __str__(self):
        return self.pos_name
    
class Employees(models.Model):
    em_name = models.CharField(max_length=55)
    em_last_name = models.CharField(max_length=55)
    em_middle_name = models.CharField(max_length=55)
    em_position = models.ForeignKey('Positions', on_delete=models.CASCADE)

    def __str__(self):
        return self.em_name

employees/forms.py
from django import forms
from .models import Employees, Positions

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employees
        fields = "__all__"
        widgets = {
            "em_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the name of the employee"
                }
            ),
            "em_last_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact name of the employee"
                }
            ),
            "em_middle_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact last name of the employee"
                }
            ),
            "em_position": forms.Select(
                attrs={
                    "type":"select", "class":"form-control"
                }
            )
        }

class UpdateEmployeeForm(forms.ModelForm):
    class Meta:
        model = Employees
        fields = "__all__"
        widgets = {
            "em_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the name of the employee"
                }
            ),
            "em_last_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact name of the employee"
                }
            ),
            "em_middle_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact last name of the employee"
                }
            ),
            "em_position": forms.Select(
                attrs={
                    "type":"select", "class":"form-control"
                }
            )
        }

class PositionsForm(forms.ModelForm):
    class Meta:
        model = Positions
        fields = "__all__"
        widgets = {
            "em_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the cpositionof the employee"
                }
            )
        }

class UpdatePositionsForm(forms.ModelForm):
    class Meta:
        model = Positions
        fields = "__all__"
        widgets = {
            "em_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the cpositionof the employee"
                }
            )
        }

employees/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import Employees, Positions
from .forms import EmployeeForm, UpdateEmployeeForm, PositionsForm, UpdatePositionsForm


# Create your views here.
#Create
class AddEmployee(generic.CreateView):
    template_name = "employees/em_create.html"
    model = Employees
    form_class = EmployeeForm
    success_url = reverse_lazy("employees:em_list")

#List
class ListEmployees(generic.View):
    template_name = "employees/em_list.html"
    context = {}

    def get(self, request, *args, **kwargs):
        employeess_list = Employees.objects.all()
        self.context = {
            "employees": employeess_list
        }

        return render(request, self.template_name, self.context)

#Details
class DetailEmployee(generic.DetailView):
    template_name = "employees/em_detail.html"
    model = Employees

#Update
class UpdateEmployee(generic.UpdateView):
    template_name = "employees/em_update.html"
    model = Employees
    form_class = UpdateEmployeeForm
    success_url = reverse_lazy("employees:em_list")

#Delete
class DeleteEmployee(generic.DeleteView):
    template_name = "employees/em_delete.html"
    model = Employees
    success_url = reverse_lazy("employees:em_list")



#Positions
#Create
class AddPosition(generic.CreateView):
    template_name = "employees/pos_create.html"
    model = Positions
    form_class = PositionsForm
    success_url = reverse_lazy("employees:pos_list")

#List
class ListPositions(generic.View):
    template_name = "employees/pos_list.html"
    context = {}

    def get(self, request, *args, **kwargs):
        positions_list = Positions.objects.all()
        self.context = {
            "positions": positions_list
        }

        return render(request, self.template_name, self.context)

#Details
class DetailPositions(generic.DetailView):
    template_name = "employees/pos_detail.html"
    model = Positions

#Update
class UpdatePositions(generic.UpdateView):
    template_name = "employees/pos_update.html"
    model = Positions
    form_class = UpdatePositionsForm
    success_url = reverse_lazy("employees:pos_list")

#Delete
class DeletePositions(generic.DeleteView):
    template_name = "employees/pos_delete.html"
    model = Positions
    success_url = reverse_lazy("employees:pos_list")

templates/employees/em_create.html
{% extends "base/base.html" %}

{% block title %}
Add Employee
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Add Employee</button>
        <a href="{% url 'employees:em_list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>
{% endblock content %}

templates/employees/em_delete.html
{% extends "base/base.html" %}

{% block title %}
Delete Employee
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post">
        {% csrf_token %}
        ¿Wish you delete: {{ object }}?
        <button type="submit" class="btn btn-primary">Delete Employee</button>
        <a href="{% url 'employees:em_list'%}" class="btn btn-warning">Cancel</a>
    </form>
<br>
{% endblock content %}

templates/employees/em_detail.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}
Details Employee
{% endblock title %}

{% block content %}
<br>
<div class="row">
  <div class="col">
    <a href="{% url 'employees:em_list' %}" class="btn btn-success d-grid">BACK TO EMPLOYEES</a>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <div class="card">
      <h5 class="card-header">{{ object.em_position }}</h5>
      <div class="card-body">
        <h5 class="card-title">INFORMATION</h5>
        <table class="table table-hover card-text">
          <thead>
            <th>FULL NAME</th>
            <th></th>
            <th></th>
          </thead>
          <tbody>
            <td>{{ object.em_name }}</td>
            <td>{{ object.em_last_name }}</td>
            <td>{{ object.em_middle_name }}</td>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<br>
{% endblock content %}

templates/employees/em_list.html
{% extends "base/base.html" %}

{% block title %}
Employees
{% endblock title %}

{% block content %}
<br>
<div class="row">
  <div class="col-6 d-grid">
    <a href="{% url 'employees:em_add' %}" class="btn btn-success ">ADD CLIENTS</a>
  </div>
  <div class="col-3 d-grid">
    <a href="{% url 'employees:pos_list' %}" class="btn btn-warning">POSITIONS</a>
  </div>
  <div class="col-3 d-grid">
    <a href="{% url 'home:index' %}" class="btn btn-secondary">HOME</a>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <table class="table table-hover table-secondary">
      <thead>
        <th>ID</th>
        <th>NAME</th>
        <th>LAST NAME</th>
        <th>MIDDLE NAME</th>
        <th>POSITION</th>
        <th></th>
        <th>ACTIONS</th>
        <th></th>
      </thead>
      <tbody>
        {% for tm in employees %}
          <tr>
            <td>{{ tm.id }}</td>
            <td>{{ tm.em_name }}</td>
            <td>{{ tm.em_last_name }}</td>
            <td>{{ tm.em_middle_name }}</td>
            <td>{{ tm.em_position }}</td>
            <td><a href="{% url 'employees:em_detail' tm.id %}" class="btn btn-info">Details</a></td>
            <td><a href="{% url 'employees:em_update' tm.id %}" class="btn btn-warning">Update</a></td>
            <td><a href="{% url 'employees:em_delete' tm.id %}" class="btn btn-primary">Delete</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<br>
{% endblock content %}

templates/employees/em_update.html
{% extends "base/base.html" %}

{% block title %}
Update Clients
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-info">Update Client</button>
        <a href="{% url 'employees:em_list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>
{% endblock content %}

templates/employees/pos_create.html
{% extends "base/base.html" %}

{% block title %}
Add Position
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Add Position</button>
        <a href="{% url 'employees:pos_list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>
{% endblock content %}

templates/employees/pos_delete.html
{% extends "base/base.html" %}

{% block title %}
Delete Position
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post">
        {% csrf_token %}
        ¿Wish you delete: {{ object }}?
        <button type="submit" class="btn btn-primary">Delete Position</button>
        <a href="{% url 'employees:pos_list'%}" class="btn btn-warning">Cancel</a>
    </form>
<br>
{% endblock content %}

templates/employees/pos_detail.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}
Details Position
{% endblock title %}

{% block content %}
<br>
<div class="row">
  <div class="col">
    <a href="{% url 'employees:pos_list' %}" class="btn btn-success d-grid">BACK TO EMPLOYEES</a>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <div class="card">
      <h5 class="card-header">POSITION</h5>
      <div class="card-body">
        <table class="table table-hover card-text">
          <thead>
            <th>DESCRIPTION</th>
          </thead>
          <tbody>
            <td>{{ object.pos_name }}</td>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<br>
{% endblock content %}

templates/employees/pos_list.html
{% extends "base/base.html" %}

{% block title %}
Positions
{% endblock title %}

{% block content %}
<br>
<div class="row">
  <div class="col-8 d-grid">
    <a href="{% url 'employees:pos_add' %}" class="btn btn-success ">ADD POSITION</a>
  </div>
  <div class="col-4 d-grid">
    <a href="{% url 'employees:em_list' %}" class="btn btn-secondary">BACK TO EMPLOYEES</a>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <table class="table table-hover table-secondary">
      <thead>
        <th>ID</th>
        <th>NAME</th>
        <th></th>
        <th>ACTIONS</th>
        <th></th>
      </thead>
      <tbody>
        {% for tm in positions %}
          <tr>
            <td>{{ tm.id }}</td>
            <td>{{ tm.pos_name }}</td>
            <td><a href="{% url 'employees:pos_detail' tm.id %}" class="btn btn-info">Details</a></td>
            <td><a href="{% url 'employees:pos_update' tm.id %}" class="btn btn-warning">Update</a></td>
            <td><a href="{% url 'employees:pos_delete' tm.id %}" class="btn btn-primary">Delete</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<br>
{% endblock content %}

templates/employees/pos_update.html
{% extends "base/base.html" %}

{% block title %}
Update Clients
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-info">Update Client</button>
        <a href="{% url 'clients:cl_list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>
{% endblock content %}