clients/urls.py
from django.urls import path
from clients import views

app_name = "clients"

urlpatterns = [
    path('list/', views.ListClients.as_view(), name="cl_list"),
    path('add/', views.AddClient.as_view(), name="cl_add"),
    path('detail/<int:pk>/', views.DetailClient.as_view(), name="cl_detail"),
    path('update/<int:pk>/', views.UpdateClient.as_view(), name="cl_update"),
    path('delete/<int:pk>/', views.DeleteClient.as_view(), name="cl_delete"),

]

home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
]

sgip/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('clients/', include('clients.urls')),
    path('employees/', include('employees.urls')),
    path('providers/', include('provider.urls')),
]

clients/models.py
from django.db import models

# Create your models here.
class Clients(models.Model):
    cl_name = models.CharField(max_length=150)
    cl_contact_name = models.CharField(max_length=55)
    cl_contact_lastname = models.CharField(max_length=55)
    cl_contact_middle_name = models.CharField(max_length=55)
    cl_contact_number_phone = models.CharField(max_length=20)

    def __str__(self):
        return self.cl_name

clients/forms.py
from django import forms
from .models import Clients

class ClientForm(forms.ModelForm):
    class Meta:
        model = Clients
        fields = "__all__"
        widgets = {
            "cl_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the name of the client"
                }
            ),
            "cl_contact_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact name of the client"
                }
            ),
            "cl_contact_lastname": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact last name of the client"
                }
            ),
            "cl_contact_middle_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact middle name of the client"
                }
            ),
            "cl_contact_number_phone": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact number phone of the client"
                }
            )
        }

class UpdateClientForm(forms.ModelForm):
    class Meta:
        model = Clients
        fields = "__all__"
        widgets = {
            "cl_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the name of the client"
                }
            ),
            "cl_contact_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact name of the client"
                }
            ),
            "cl_contact_lastname": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact last name of the client"
                }
            ),
            "cl_contact_middle_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact middle name of the client"
                }
            ),
            "cl_contact_number_phone": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact number phone of the client"
                }
            )
        }

clients/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import Clients
from .forms import ClientForm, UpdateClientForm


# Create your views here.
#Create
class AddClient(generic.CreateView):
    template_name = "clients/cl_create.html"
    model = Clients
    form_class = ClientForm
    success_url = reverse_lazy("clients:cl_list")

#List
class ListClients(generic.View):
    template_name = "clients/cl_list.html"
    context = {}

    def get(self, request, *args, **kwargs):
        client_list = Clients.objects.all()
        self.context = {
            "clients": client_list
        }

        return render(request, self.template_name, self.context)

#Details
class DetailClient(generic.DetailView):
    template_name = "clients/cl_detail.html"
    model = Clients

#Update
class UpdateClient(generic.UpdateView):
    template_name = "clients/cl_update.html"
    model = Clients
    form_class = UpdateClientForm
    success_url = reverse_lazy("clients:cl_list")

#Delete
class DeleteClient(generic.DeleteView):
    template_name = "clients/cl_delete.html"
    model = Clients
    success_url = reverse_lazy("clients:cl_list")

templates/clients/cl_create.html
{% extends "base/base.html" %}

{% block title %}
Add Clients
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Add Client</button>
        <a href="{% url 'clients:cl_list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>
{% endblock content %}

templates/clients/cl_delete.html
{% extends "base/base.html" %}

{% block title %}
Delete Client
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post">
        {% csrf_token %}
        ¿Wish you delete: {{ object }}?
        <button type="submit" class="btn btn-primary">Delete Client</button>
        <a href="{% url 'clients:cl_list'%}" class="btn btn-warning">Cancel</a>
    </form>
<br>
{% endblock content %}

templates/clients/cl_detail.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}
Details Clients
{% endblock title %}

{% block content %}
<br>
<div class="row">
  <div class="col">
    <a href="{% url 'clients:cl_list' %}" class="btn btn-success d-grid">BACK TO CLIENTS</a>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <div class="card">
      <h5 class="card-header">{{ object.cl_name }}</h5>
      <div class="card-body">
        <h5 class="card-title">CONTACT</h5>
        <table class="table table-hover card-text">
          <thead>
            <th>FULL NAME</th>
            <th></th>
            <th></th>
            <th>NUMBER PHONE</th>
          </thead>
          <tbody>
            <td>{{ object.cl_contact_name }}</td>
            <td>{{ object.cl_contact_lastname }}</td>
            <td>{{ object.cl_contact_middle_name }}</td>
            <td>{{ object.cl_contact_number_phone }}</td>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<br>
{% endblock content %}

templates/clients/cl_list.html
{% extends "base/base.html" %}

{% block title %}
Clients
{% endblock title %}

{% block content %}
<br>
<div class="row">
  <div class="col-8 d-grid">
    <a href="{% url 'clients:cl_add' %}" class="btn btn-success ">ADD CLIENTS</a>
  </div>
  <div class="col-4 d-grid">
    <a href="{% url 'home:index' %}" class="btn btn-secondary">HOME</a>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <table class="table table-hover table-secondary">
      <thead>
        <th>ID</th>
        <th>NAME</th>
        <th>CONTACT NAME</th>
        <th>CONTACT LAST NAME</th>
        <th>CONTACT MIDDLE NAME</th>
        <th>CONTACT NUMBER PHONE</th>
        <th></th>
        <th>ACTIONS</th>
        <th></th>
      </thead>
      <tbody>
        {% for tm in clients %}
          <tr>
            <td>{{ tm.id }}</td>
            <td>{{ tm.cl_name }}</td>
            <td>{{ tm.cl_contact_name }}</td>
            <td>{{ tm.cl_contact_lastname }}</td>
            <td>{{ tm.cl_contact_middle_name }}</td>
            <td>{{ tm.cl_contact_number_phone }}</td>
            <td><a href="{% url 'clients:cl_detail' tm.id %}" class="btn btn-info">Details</a></td>
            <td><a href="{% url 'clients:cl_update' tm.id %}" class="btn btn-warning">Update</a></td>
            <td><a href="{% url 'clients:cl_delete' tm.id %}" class="btn btn-primary">Delete</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<br>
{% endblock content %}

templates/clients/cl_update.html
{% extends "base/base.html" %}

{% block title %}
Update Clients
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-info">Update Client</button>
        <a href="{% url 'clients:cl_list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>
{% endblock content %}