home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
]

provider/urls.py
from django.urls import path
from provider import views

app_name = "provider"

urlpatterns = [
    path('list/', views.ListProvider.as_view(), name="pr_list"),
    path('add/', views.AddProvider.as_view(), name="pr_add"),
    path('detail/<int:pk>/', views.DetailProvider.as_view(), name="pr_detail"),
    path('update/<int:pk>/', views.UpdateProvider.as_view(), name="pr_update"),
    path('delete/<int:pk>/', views.DeleteProvider.as_view(), name="pr_delete"),
]

sgip/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('clients/', include('clients.urls')),
    path('employees/', include('employees.urls')),
    path('providers/', include('provider.urls')),
]

provider/models.py
from django.db import models

# Create your models here.
class Providers(models.Model):
    pr_name = models.CharField(max_length=150)
    pr_contact_name = models.CharField(max_length=55)
    pr_contact_lastname = models.CharField(max_length=55)
    pr_contact_middle_name = models.CharField(max_length=55)
    pr_contact_number_phone = models.CharField(max_length=20)

    def __str__(self):
        return self.pr_name

provider/forms.py
from django import forms
from .models import Providers

class ProviderForm(forms.ModelForm):
    class Meta:
        model = Providers
        fields = "__all__"
        widgets = {
            "pr_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the name of the client"
                }
            ),
            "pr_contact_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact name of the client"
                }
            ),
            "pr_contact_lastname": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact last name of the client"
                }
            ),
            "pr_contact_middle_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact middle name of the client"
                }
            ),
            "pr_contact_number_phone": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact number phone of the client"
                }
            )
        }

class UpdateProviderForm(forms.ModelForm):
    class Meta:
        model = Providers
        fields = "__all__"
        widgets = {
            "pr_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the name of the client"
                }
            ),
            "pr_contact_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact name of the client"
                }
            ),
            "pr_contact_lastname": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact last name of the client"
                }
            ),
            "pr_contact_middle_name": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact middle name of the client"
                }
            ),
            "pr_contact_number_phone": forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control", "placeholder":"Insert the contact number phone of the client"
                }
            )
        }

provider/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import Providers
from .forms import ProviderForm, UpdateProviderForm


# Create your views here.
#Create
class AddProvider(generic.CreateView):
    template_name = "providers/pr_create.html"
    model = Providers
    form_class = ProviderForm
    success_url = reverse_lazy("provider:pr_list")

#List
class ListProvider(generic.View):
    template_name = "providers/pr_list.html"
    context = {}

    def get(self, request, *args, **kwargs):
        providers_list = Providers.objects.all()
        self.context = {
            "providers": providers_list
        }

        return render(request, self.template_name, self.context)

#Details
class DetailProvider(generic.DetailView):
    template_name = "providers/pr_detail.html"
    model = Providers

#Update
class UpdateProvider(generic.UpdateView):
    template_name = "providers/pr_update.html"
    model = Providers
    form_class = UpdateProviderForm
    success_url = reverse_lazy("provider:pr_list")

#Delete
class DeleteProvider(generic.DeleteView):
    template_name = "providers/pr_delete.html"
    model = Providers
    success_url = reverse_lazy("provider:pr_list")

templates/providers/pr_create.html
{% extends "base/base.html" %}

{% block title %}
Add Providers
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Add Client</button>
        <a href="{% url 'provider:pr_list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>
{% endblock content %}

templates/providers/pr_delete.html
{% extends "base/base.html" %}

{% block title %}
Delete Providers
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post">
        {% csrf_token %}
        ¿Wish you delete: {{ object }}?
        <button type="submit" class="btn btn-primary">Delete Providers</button>
        <a href="{% url 'provider:pr_list'%}" class="btn btn-warning">Cancel</a>
    </form>
<br>
{% endblock content %}

templates/providers/pr_detail.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}
Details Providers
{% endblock title %}

{% block content %}
<br>
<div class="row">
  <div class="col">
    <a href="{% url 'provider:pr_list' %}" class="btn btn-success d-grid">BACK TO CLIENTS</a>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <div class="card">
      <h5 class="card-header">{{ object.pr_name }}</h5>
      <div class="card-body">
        <h5 class="card-title">CONTACT</h5>
        <table class="table table-hover card-text">
          <thead>
            <th>FULL NAME</th>
            <th></th>
            <th></th>
            <th>NUMBER PHONE</th>
          </thead>
          <tbody>
            <td>{{ object.pr_contact_name }}</td>
            <td>{{ object.pr_contact_lastname }}</td>
            <td>{{ object.pr_contact_middle_name }}</td>
            <td>{{ object.pr_contact_number_phone }}</td>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<br>
{% endblock content %}

templates/providers/pr_list.html
{% extends "base/base.html" %}

{% block title %}
Providers
{% endblock title %}

{% block content %}
<br>
<div class="row">
  <div class="col-8 d-grid">
    <a href="{% url 'provider:pr_add' %}" class="btn btn-success ">ADD PROVIDER</a>
  </div>
  <div class="col-4 d-grid">
    <a href="{% url 'home:index' %}" class="btn btn-secondary">HOME</a>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <table class="table table-hover table-secondary">
      <thead>
        <th>ID</th>
        <th>NAME</th>
        <th>CONTACT NAME</th>
        <th>CONTACT LAST NAME</th>
        <th>CONTACT MIDDLE NAME</th>
        <th>CONTACT NUMBER PHONE</th>
        <th></th>
        <th>ACTIONS</th>
        <th></th>
      </thead>
      <tbody>
        {% for tm in providers %}
          <tr>
            <td>{{ tm.id }}</td>
            <td>{{ tm.pr_name }}</td>
            <td>{{ tm.pr_contact_name }}</td>
            <td>{{ tm.pr_contact_lastname }}</td>
            <td>{{ tm.pr_contact_middle_name }}</td>
            <td>{{ tm.pr_contact_number_phone }}</td>
            <td><a href="{% url 'provider:pr_detail' tm.id %}" class="btn btn-info">Details</a></td>
            <td><a href="{% url 'provider:pr_update' tm.id %}" class="btn btn-warning">Update</a></td>
            <td><a href="{% url 'provider:pr_delete' tm.id %}" class="btn btn-primary">Delete</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<br>
{% endblock content %}

templates/providers/pr_update.html
{% extends "base/base.html" %}

{% block title %}
Update Providers
{% endblock title %}

{% block content %}
<br>
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-info">Update Providers</button>
        <a href="{% url 'provider:pr_list' %}" class="btn btn-primary">Cancel</a>
    </form>
<br>
{% endblock content %}